spring.application.name=superball

# DATABASE (Render PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT}

# IMPORTANT for Render (not localhost)
app.base-url=https://superball-backend.onrender.com

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=p9Q3v1QmJk9m0xq8Qz9l3h8y7m1n4k5p6q7r8s9t0=
jwt.expiration=86400000

# MAIL (NO CHANGE)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=biat.service.clientele@gmail.com
spring.mail.password=hwhm txze zval fzyp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
